name: Deploy documentation 

on:
  push:
    branches:
      - main

jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: NPM install
      run: npm ci

    - name: Build packages
      run: npm run build

    - name: Generate fidelity artifacts 
      continue-on-error: true
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm run test

    - name: Stage documentation artifacts
      run: ./scripts/ci-before-deploy.sh

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        force_orphan: true
        publish_dir: ./dist
